### ISSUE TITLE
连接mcl-1.2.2时失败

### ISSUE THREAD

**Issue by GardenHamster** [Executor-Cheng/Mirai-CSharp#108]
mcl-1.1.0下能连接成功,也能收发消息，换成mcl-1.2.2后就不行了

![image](https://user-images.githubusercontent.com/89188316/148165325-7f996649-b534-41a8-b946-82200822875c.png)

![image](https://user-images.githubusercontent.com/89188316/148165376-bdfafe4d-0459-4aad-95bd-7288750aae05.png)

```
System.AggregateException:“One or more errors occurred. (The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.)”

   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.<ParseAsyncCore>d__57.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at Mirai.CSharp.HttpApi.Extensions.HttpClientExtensions.<GetJsonAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult()
   at Mirai.CSharp.HttpApi.Session.MiraiHttpSession.<GetVersionAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult()
   at Mirai.CSharp.HttpApi.Session.MiraiHttpSession.<ConnectAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Theresa3rd_Bot.MiraiHelper.<ConnectMirai>d__0.MoveNext() in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\MiraiHelper.cs:line 52

   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Theresa3rd_Bot.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in D:\project\Theresa3rd-Bot\Theresa3rd-Bot\Startup.cs:line 61
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()
```

**Comment by Executor-Cheng** [comment]
照这个错误堆栈来看, 异常发生于方法 `MiraiHttpSession.GetVersionAsync` 中
不知道为啥, 你的 `mirai-api-http` 未能对接口调用发送正确的响应, 响应内容为空
我自己用的非mcl加载, 刚把 mirai 的各项组件都改为了 v2.9.1, 未能复现问题
这样子吧, 你自己调用一下以下接口, 看看 `mirai-api-http` 返回了什么 `HttpStatus` 和 `Body`:
`http://<域名或IP>:<端口>/about`
`域名/IP` 和 `端口` 与你在自己项目中设置的一致

**Comment by GardenHamster** [comment]
谢谢dalao,是我自己的锅,排查了一下已经解决了,现在就关闭这个issues
