### ISSUE TITLE
IMiraiHttpSession.GetFriendListAsync 报错

### ISSUE THREAD

**Issue by developer-ken** [Executor-Cheng/Mirai-CSharp#116]
```
//session在初始化时获得，并存储在static变量中
session.GetFriendListAsync();//此行报错
```
报错：
```
One or more errors occurred. (The requested operation requires an element of type 'Object', but the target element has type 'Array'.)
Stack:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at tech.msgp.groupmanager.Code.DataBase.update_groupmembers(Int64 g) in D:\Development\ManagementBot\tech.msgp.groupmanager.Code\DataBase.cs:line 1046
```

**Comment by Executor-Cheng** [comment]
麻烦提供一下所用的 `mirai-api-http` 版本

**Comment by developer-ken** [comment]
之前出错时使用的是net.mamoe.mirai-api-http v1.10.0
我尝试了更新到v1.12.0，仍然存在报错

**Comment by developer-ken** [comment]
抓包结果似乎没有问题
```
HTTP/1.1 200 OK
Date: Fri, 28 Jan 2022 07:10:26 GMT
Server: Ktor/debug
Content-Length: 1479
Content-Type: application/json; charset=UTF-8

[{"id":66600000,"nickname":"babyQ","remark":"babyQ"},....{"id":3447974198,"nickname":"XCaiiii_-","remark":"XCaiiii_-"}]
```

**Comment by Executor-Cheng** [comment]
已明确问题, 未能向下兼容 `mirai-api-http` v1.X 版本
稍后会进行修复

**Comment by developer-ken** [comment]
将mirai-api-http升级到2后，在Windows上成功跑通。
但当部署到Linux服务器后，出现新异常
```
Specified argument was out of the range of valid values.
   at System.Text.Json.JsonDocument.GetRawValue(Int32 index, Boolean includeQuotes)
   at Mirai.CSharp.HttpApi.Utility.Utils.GetRawdata(JsonDocument j, Int32 idx, Boolean includeQuotes)
   at Mirai.CSharp.HttpApi.Utility.Utils.Deserialize[T](JsonElement element, JsonSerializerOptions options)
   at Mirai.CSharp.HttpApi.Extensions.ApiResponseExtensions.AsApiRespV2Async[TResult,TImpl](Task`1 responseTask, CancellationToken token)
```

**Comment by Executor-Cheng** [comment]
> 将mirai-api-http升级到2后，在Windows上成功跑通。 但当部署到Linux服务器后，出现新异常
> 
> ```
> Specified argument was out of the range of valid values.
>    at System.Text.Json.JsonDocument.GetRawValue(Int32 index, Boolean includeQuotes)
>    at Mirai.CSharp.HttpApi.Utility.Utils.GetRawdata(JsonDocument j, Int32 idx, Boolean includeQuotes)
>    at Mirai.CSharp.HttpApi.Utility.Utils.Deserialize[T](JsonElement element, JsonSerializerOptions options)
>    at Mirai.CSharp.HttpApi.Extensions.ApiResponseExtensions.AsApiRespV2Async[TResult,TImpl](Task`1 responseTask, CancellationToken token)
> ```

辛苦提供一下所用.NET的版本

**Comment by developer-ken** [comment]
编译时的目标平台是.NET5

**Comment by Executor-Cheng** [comment]
已查明问题。
在Linux下, JIT生成的本地方法签名和在Windows下略有不同。
https://github.com/Executor-Cheng/Mirai-CSharp/blob/3ec8fdb623664488a77a25fbcf7bc50e39a7629f/Mirai-CSharp.HttpApi/Utility/Utils.cs#L33

在Linux下, 方法指针类型应为
`delegate*<JsonDocument, int, bool, ReadOnlyMemory<byte>>`
我得想想看怎么处理这两个之间的差异

**Comment by Executor-Cheng** [comment]
已在 Executor-Cheng/Mirai-CSharp@033b9e3 中修复
