### ISSUE TITLE
如何让Bot发送一条自定义转发消息？

### ISSUE THREAD

**Issue by q2398003522** [Executor-Cheng/Mirai-CSharp#132]
我尝试new一个ForwardMessage，然后将信息填入，代码如下：
```
var nodes = new List<ForwardMessageNode>();
foreach (var str in Constants.Messages.Help)
{
    nodes.Add(new ForwardMessageNode
    {
        QQNumber = XeronPlugin.BotId, // XeronPlugin.BotId是long类型常量，Bot的QQ号
        Name = XeronPlugin.BotName, // XeronPlugin.BotName是string类型常量
        Time = DateTime.Now, // 当前时间
        Chain = new IChatMessage[]
        {
            new PlainMessage(str), // 文字消息
        },
    });
}
await session.SendGroupMessageAsync(e.Sender.Group.Id, new IChatMessage[]
{
    new ForwardMessage(nodes.ToArray()),
});
```
但最后SendGroupMessageAsync出错：Mirai.CSharp.HttpApi.Exceptions.UnknownResponseException:“未知的服务器返回。”
Mirai后台也报错了：
```
2022-08-16 11:55:57 E/MAH Access: java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.sendSinglePacket(GeneralMessageSenderProtocol.kt:146)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.access$sendSinglePacket(GeneralMessageSenderProtocol.kt:46)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender$sendSinglePacket$1.invokeSuspend(GeneralMessageSenderProtocol.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
是不是发送转发消息的功能还在开发中？

**Comment by Executor-Cheng** [comment]
没错，是一个bug，序列化 `ForwardMessage` 的时候，其下的 `Nodes` 未能被正确序列化

**Comment by Executor-Cheng** [comment]
问题已解决，2.1.8版本将于近期发布，我要想想看能不能做一个 `(I)ForwardMessageBuilder` 出来

**Comment by q2398003522** [comment]
好的

**Comment by Executor-Cheng** [comment]
已完成, 在2.1.8版本你可以尝试这样写:
```csharp
IMessageChainBuilder builder = session.GetMessageChainBuilder();
IForwardMessageBuilder fwdBuilder = builder.GetForwardMessageBuilder();
foreach (var str in Constants.Messages.Help)
{
    IMessageChainBuilder fwdChainBuilder = session.GetMessageChainBuilder();
    fwdChainBuilder.AddPlainMessage(str);
    fwdBuilder.AddNode(XeronPlugin.BotName, XeronPlugin.BotId, DateTime.Now, fwdChainBuilder);
}
builder.AddForwardMessage(fwdBuilder);
await session.SendGroupMessageAsync(e.Sender.Group.Id, builder);
```
