### ISSUE TITLE
每隔一段时间Bot收到的消息不会触发收到消息的事件

### ISSUE THREAD

**Issue by Nijikuu** [Executor-Cheng/Mirai-CSharp#56]
如题，也试过Mirai-Csharp-Example单独运行，刚开始能正常打印消息，隔一段时间后bot收到消息就不能正常打印
MiraiCsharp版本1.0.2.1
MiraiHttp版本1.12.0
Mirai版本2.7M2

注：另一个使用2.3.2Mirai，1.9.7http的bot则无此问题
希望能找出问题并修复，辛苦了

**Comment by MizunaNako** [comment]
掉线原因是这个，未知的消息类型，请尽快适配该类消息，非常感谢，辛苦了（Forward事什么消息？）
`System.NotImplementedException: 未知的消息类型:Forward
   at Mirai_CSharp.Utility.JsonConverters.IMessageBaseArrayConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at Mirai_CSharp.Utility.Utils.Deserialize[T](JsonElement& element, JsonSerializerOptions options)
   at Mirai_CSharp.MiraiHttpSession.ReceiveMessageLoop(InternalSessionInfo session, CancellationToken token)`

**Comment by Executor-Cheng** [comment]
可能和#55 是同一个问题
根据你提供的堆栈来看, 由于无法解析转发消息导致连接被断开, 当前版本的`Mirai-CSharp`可能无法正确触发ws离线的事件
