### ISSUE TITLE
最新的预览版还是不行

### ISSUE THREAD

**Issue by aion1998** [Executor-Cheng/Mirai-CSharp#64]
版本：
![image](https://user-images.githubusercontent.com/19725014/134802573-f0965c85-c9b4-480b-b0fd-27e517b21351.png)

然后全是红色的：
![image](https://user-images.githubusercontent.com/19725014/134802593-2f0004df-16a5-4df7-b927-9ebb7dcb297c.png)

**Comment by aion1998** [comment]
啊，对了，代码我是复制源码里面的例子项目

**Comment by Executor-Cheng** [comment]
同样的方法再添加一个 `Mirai-CSharp.HttpApi` 包

**Comment by aion1998** [comment]
嗦嘎，我这个可以去掉吗
![image](https://user-images.githubusercontent.com/19725014/134802903-735b4c87-e58c-4a36-b530-1e9bcba6fdc2.png)

**Comment by Executor-Cheng** [comment]
实现了 `(I)MiraiHttpMessageHandler<TMessage>` 或 `(I)DedicateMiraiHttpMessageHandler<TMessage>` 的Handler应该在 `AddDefaultMiraiHttpFramework` 下边注册
实现了 `(I)MiraiMessageHandler<TMessage>` 或 `(I)DedicateMiraiMessageHandler<TMessage>` 的Handler应该在 `AddMiraiBaseFramework` 下边注册

**Comment by aion1998** [comment]
!不可以用mirai 2.0的版本吗，我发现连不上

**Comment by aion1998** [comment]
![Uploading image.png…]()
版本

**Comment by Executor-Cheng** [comment]
理应上下兼容, 你的图裂了, 先检查一下

**Comment by aion1998** [comment]
就是一直报超时

**Comment by Executor-Cheng** [comment]
超时是你的网络配置有问题
检查服务器防火墙有没有正确配置

**Comment by aion1998** [comment]
不至于，我就摸鱼偶然看到版本更新了，就换了下代码，我再康康

**Comment by aion1998** [comment]
打咩，打咩哟
完全连不上，一直是计算机积极拒绝，阿里云后台端口是全开放，其他东西的访问也没毛病，不知道啥情况了

**Comment by Executor-Cheng** [comment]
这种情况，IP或者端口填错的概率最大了
确认一次 `mirai-api-http` 配置文件中的端口和你在注册服务时填写的IP、端口是否一致

**Comment by aion1998** [comment]
一模一样，我这之前都快运行了好久了

**Comment by aion1998** [comment]
。。等下，那个host要加hhtp吗？

**Comment by Executor-Cheng** [comment]
当然不用啊。。
域名就是域名

**Comment by aion1998** [comment]
我也没加

**Comment by aion1998** [comment]
```
2021-09-26 18:38:49 E/Mirai HTTP API: java.lang.NoSuchMethodError: 'double kotli
n.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java
.util.concurrent.TimeUnit)'
        at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.k
t:48)
        at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.k
t)
        at io.ktor.features.CORS$Feature.install(CORS.kt:517)
        at io.ktor.features.CORS$Feature.install(CORS.kt:509)
        at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.k
t:68)
        at net.mamoe.mirai.api.http.route.BaseRouteKt.mirai(BaseRoute.kt:45)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiH
ttpAPIServer.kt:93)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiH
ttpAPIServer.kt:29)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantia
teAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:303)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApp
lication(ApplicationEngineEnvironmentReloading.kt:138)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(App
licationEngineEnvironmentReloading.kt:270)
        at io.ktor.server.cio.CIOApplicationEngine$serverJob$1$1.invokeSuspend(C
IOApplicationEngine.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
Scheduler.kt:665)

```

才发现mcl启动的时候有个报错，感觉就是这个原因了

**Comment by Executor-Cheng** [comment]
这样的话就更新吧

**Comment by aion1998** [comment]
前面的搞定的，是因为httpapi那个插件没自动更新

**Comment by aion1998** [comment]
然后启动还是失败，是一个新错误
![image](https://user-images.githubusercontent.com/19725014/134848500-f6ec83f4-0d8d-4576-ac28-e0331ae08e7e.png)

如图

**Comment by aion1998** [comment]
@Executor-Cheng

**Comment by Executor-Cheng** [comment]
发一下详细的堆栈信息和 mirai-api-http 的版本号

**Comment by aion1998** [comment]
mirai-api-http版本：mirai-api-http-v2.3.1.mirai

异常信息：
```
 Message:'<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.

   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.<ParseAsyncCore>d__57.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Mirai.CSharp.HttpApi.Extensions.HttpClientExtensions.<GetJsonAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Mirai.CSharp.HttpApi.Session.MiraiHttpSession.<GetVersionAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Mirai.CSharp.HttpApi.Session.MiraiHttpSession.<ConnectAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GreatMing.Bot.Program.<Main>d__0.MoveNext() in D:\ln\925Project\LN.Git\Gitee2021\NewGreatMing\GreatMing\GreatMing.Bot\Program.cs:line 50
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at GreatMing.Bot.Program.<Main>d__0.MoveNext() in D:\ln\925Project\LN.Git\Gitee2021\NewGreatMing\GreatMing\GreatMing.Bot\Program.cs:line 51
```

**Comment by aion1998** [comment]
哎，没事了，上面是开了代理导致的
前面连不上的原因是那插件问题，插件配置的host要设置为 0.0.00
[关于mirai-api-http2.0版本的host设置问题](https://github.com/project-mirai/mirai-api-http/issues/481)

**Comment by Executor-Cheng** [comment]
我就说什么时候它还会返回一个html给我的
解决了就好了
